/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DevStatesRouteImport } from './routes/dev.states'
import { Route as RolesIdRouteImport } from './routes/roles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStatesRoute = DevStatesRouteImport.update({
  id: '/dev/states',
  path: '/dev/states',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdRoute = RolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/dev/states': typeof DevStatesRoute
  '/roles/$id': typeof RolesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/dev/states': typeof DevStatesRoute
  '/roles/$id': typeof RolesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/dev/states': typeof DevStatesRoute
  '/roles/$id': typeof RolesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ask' | '/settings' | '/api/$' | '/dev/states' | '/roles/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/settings' | '/api/$' | '/dev/states' | '/roles/$id'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/settings'
    | '/api/$'
    | '/dev/states'
    | '/roles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  SettingsRoute: typeof SettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DevStatesRoute: typeof DevStatesRoute
  RolesIdRoute: typeof RolesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/states': {
      id: '/dev/states'
      path: '/dev/states'
      fullPath: '/dev/states'
      preLoaderRoute: typeof DevStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id': {
      id: '/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof RolesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  SettingsRoute: SettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
  DevStatesRoute: DevStatesRoute,
  RolesIdRoute: RolesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
