"""Baseline persistence schema — workspaces through provider accounting."""

from __future__ import annotations

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "4569bacdd3ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_conversations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_workspace_id', 'conversations', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('normalised_text', sa.Text(), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('cv', 'job_description', 'cover_letter')", name=op.f('ck_documents_document_kind')),
    sa.CheckConstraint("parse_status IN ('parsed', 'failed')", name=op.f('ck_documents_parse_status')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_workspace_id', 'documents', ['workspace_id'], unique=False)
    op.create_index('uq_documents_one_active_cv', 'documents', ['workspace_id'], unique=True, postgresql_where=sa.text("kind = 'cv' AND is_active IS TRUE"))
    op.create_table('provider_call_accounting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_tag', sa.String(length=128), nullable=False),
    sa.Column('left_machine', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_provider_call_accounting_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_call_accounting'))
    )
    op.create_index('ix_provider_call_accounting_workspace_id', 'provider_call_accounting', ['workspace_id'], unique=False)
    op.create_table('provider_settings',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('completion_provider', sa.String(length=64), nullable=False),
    sa.Column('embedding_provider', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_provider_settings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', name=op.f('pk_provider_settings'))
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_chunks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('ix_chunks_workspace_id', 'chunks', ['workspace_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('competency', sa.String(length=128), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('duration_signal', sa.String(length=64), nullable=True),
    sa.Column('recency_signal', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_claims_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_claims_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_workspace_id', 'claims', ['workspace_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('client_request_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_questions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_questions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('workspace_id', 'client_request_id', name='uq_questions_workspace_client_request')
    )
    op.create_index('ix_questions_workspace_id', 'questions', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('job_description_document_id', sa.UUID(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_document_id'], ['documents.id'], name=op.f('fk_roles_job_description_document_id_documents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_roles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index('ix_roles_workspace_id', 'roles', ['workspace_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_spans_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_spans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spans'))
    )
    op.create_index('ix_spans_workspace_id', 'spans', ['workspace_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_analysis_jobs_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analysis_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index('ix_analysis_jobs_workspace_id', 'analysis_jobs', ['workspace_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_tag', sa.String(length=128), nullable=False),
    sa.Column('left_machine', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_answers_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('question_id', name='uq_answers_one_per_question')
    )
    op.create_index('ix_answers_workspace_id', 'answers', ['workspace_id'], unique=False)
    op.create_table('claim_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_spans_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_claim_spans_span_id_spans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_claim_spans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_spans')),
    sa.UniqueConstraint('claim_id', 'span_id', name='uq_claim_spans_pair')
    )
    op.create_index('ix_claim_spans_workspace_id', 'claim_spans', ['workspace_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_tag', sa.String(length=128), nullable=False),
    sa.Column('left_machine', sa.Boolean(), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=64), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_embeddings_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_embeddings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index('ix_embeddings_workspace_id', 'embeddings', ['workspace_id'], unique=False)
    op.create_table('generated_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_tag', sa.String(length=128), nullable=False),
    sa.Column('left_machine', sa.Boolean(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_generated_drafts_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_generated_drafts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_drafts'))
    )
    op.create_index('ix_generated_drafts_workspace_id', 'generated_drafts', ['workspace_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('competency', sa.String(length=128), nullable=False),
    sa.Column('must_have', sa.Boolean(), nullable=False),
    sa.Column('source_span_id', sa.UUID(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('is_vague', sa.Boolean(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_requirements_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_span_id'], ['spans.id'], name=op.f('fk_requirements_source_span_id_spans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_requirements_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    op.create_index('ix_requirements_workspace_id', 'requirements', ['workspace_id'], unique=False)
    op.create_table('score_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=32), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_score_explanations_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_score_explanations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_explanations')),
    sa.UniqueConstraint('role_id', 'analysis_version', name='uq_score_explanations_role_version')
    )
    op.create_index('ix_score_explanations_workspace_id', 'score_explanations', ['workspace_id'], unique=False)
    op.create_table('answer_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answer_citations_answer_id_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_answer_citations_span_id_spans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_answer_citations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_citations')),
    sa.UniqueConstraint('answer_id', 'span_id', name='uq_answer_citations_pair')
    )
    op.create_index('ix_answer_citations_workspace_id', 'answer_citations', ['workspace_id'], unique=False)
    op.create_table('draft_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['generated_drafts.id'], name=op.f('fk_draft_citations_draft_id_generated_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_draft_citations_span_id_spans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_draft_citations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_citations')),
    sa.UniqueConstraint('draft_id', 'span_id', name='uq_draft_citations_pair')
    )
    op.create_index('ix_draft_citations_workspace_id', 'draft_citations', ['workspace_id'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('analysis_version', sa.Integer(), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_mappings_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_mappings_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mappings_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mappings')),
    sa.UniqueConstraint('role_id', 'requirement_id', 'analysis_version', name='uq_mappings_role_requirement_version')
    )
    op.create_index('ix_mappings_workspace_id', 'mappings', ['workspace_id'], unique=False)
    op.create_table('mapping_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['mappings.id'], name=op.f('fk_mapping_spans_mapping_id_mappings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], name=op.f('fk_mapping_spans_span_id_spans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_mapping_spans_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_spans')),
    sa.UniqueConstraint('mapping_id', 'span_id', name='uq_mapping_spans_pair')
    )
    op.create_index('ix_mapping_spans_workspace_id', 'mapping_spans', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mapping_spans_workspace_id', table_name='mapping_spans')
    op.drop_table('mapping_spans')
    op.drop_index('ix_mappings_workspace_id', table_name='mappings')
    op.drop_table('mappings')
    op.drop_index('ix_draft_citations_workspace_id', table_name='draft_citations')
    op.drop_table('draft_citations')
    op.drop_index('ix_answer_citations_workspace_id', table_name='answer_citations')
    op.drop_table('answer_citations')
    op.drop_index('ix_score_explanations_workspace_id', table_name='score_explanations')
    op.drop_table('score_explanations')
    op.drop_index('ix_requirements_workspace_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_generated_drafts_workspace_id', table_name='generated_drafts')
    op.drop_table('generated_drafts')
    op.drop_index('ix_embeddings_workspace_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_claim_spans_workspace_id', table_name='claim_spans')
    op.drop_table('claim_spans')
    op.drop_index('ix_answers_workspace_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_analysis_jobs_workspace_id', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('ix_spans_workspace_id', table_name='spans')
    op.drop_table('spans')
    op.drop_index('ix_roles_workspace_id', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_questions_workspace_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_claims_workspace_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_chunks_workspace_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('provider_settings')
    op.drop_index('ix_provider_call_accounting_workspace_id', table_name='provider_call_accounting')
    op.drop_table('provider_call_accounting')
    op.drop_index('uq_documents_one_active_cv', table_name='documents', postgresql_where=sa.text("kind = 'cv' AND is_active IS TRUE"))
    op.drop_index('ix_documents_workspace_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_workspace_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('workspaces')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
